### ISSUE TITLE
Breaking words

### ISSUE THREAD

**Issue by robinmetral** [wp-graphql/gatsby-wpgraphql-blog-example#1]
Hi :wave: 

Loving the idea behind `wp-graphql`, thank you for sharing!

Small first issue here, words within post content are being broken onto different lines:

![screenshot_2019-02-26 sticky](https://user-images.githubusercontent.com/35560568/53396990-3222b300-39a6-11e9-9393-93f291eb4e76.png)

**Comment by jasonbahl** [comment]
Oh no! I think I put a style in to `break-all`, instead of `break-word`

I’ll check it out. 

Thanks for reporting and thanks for your interest in WPGraphQL. Excited to see what you can build with it!
